import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/providers";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider, CssBaseline } from '@mui/material';
import CustomThemeProvider from "@/themes/CustomThemeProvider";

export const metadata: Metadata = {
  title: "Woki - Movies app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppRouterCacheProvider>
           <CustomThemeProvider>
              <CssBaseline />
              {children}
            </CustomThemeProvider>
          </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
